/**
 * O'zbekiston ma'muriy-hududiy bo'linishi — hududlar ma'lumotnomasini bir marta to'ldirish uchun.
 *
 * Ro'yxat 14 ta yuqori birlikdan iborat: 12 viloyat, Qoraqalpog'iston Respublikasi va Toshkent shahri.
 * Har birida tumanlar va viloyat tobeligidagi shaharlar (Toshkent shahrida — tumanlari) beriladi.
 *
 * Bu — BOSHLANG'ICH ro'yxat: nomlar lotin alifbosida, kompaniya o'ziga qulay qilib tuzatishi
 * (nomini o'zgartirishi, keraksizini o'chirishi, yangisini qo'shishi) mumkin. Yuklash faqat YETISHMAYOTGAN
 * yozuvni qo'shadi va viloyatsiz turgan mavjud tumanni o'z viloyatiga bog'laydi — hech narsa o'chirilmaydi.
 */
export type UzbekistanRegion = { name: string; districts: string[] };

export const UZBEKISTAN_REGIONS: UzbekistanRegion[] = [
  {
    name: "Qoraqalpog'iston Respublikasi",
    districts: [
      "Nukus",
      "Taxiatosh",
      "Amudaryo tumani",
      "Beruniy tumani",
      "Chimboy tumani",
      "Ellikqal'a tumani",
      "Kegeyli tumani",
      "Mo'ynoq tumani",
      "Nukus tumani",
      "Qanliko'l tumani",
      "Qo'ng'irot tumani",
      "Qorao'zak tumani",
      "Shumanay tumani",
      "Taxtako'pir tumani",
      "To'rtko'l tumani",
      "Xo'jayli tumani",
    ],
  },
  {
    name: "Andijon viloyati",
    districts: [
      "Andijon",
      "Xonobod",
      "Andijon tumani",
      "Asaka tumani",
      "Baliqchi tumani",
      "Bo'ston tumani",
      "Buloqboshi tumani",
      "Izboskan tumani",
      "Jalaquduq tumani",
      "Marhamat tumani",
      "Oltinko'l tumani",
      "Paxtaobod tumani",
      "Qo'rg'ontepa tumani",
      "Shahrixon tumani",
      "Ulug'nor tumani",
      "Xo'jaobod tumani",
    ],
  },
  {
    name: "Buxoro viloyati",
    districts: [
      "Buxoro",
      "Kogon",
      "Buxoro tumani",
      "G'ijduvon tumani",
      "Jondor tumani",
      "Kogon tumani",
      "Olot tumani",
      "Peshku tumani",
      "Qorako'l tumani",
      "Qorovulbozor tumani",
      "Romitan tumani",
      "Shofirkon tumani",
      "Vobkent tumani",
    ],
  },
  {
    name: "Farg'ona viloyati",
    districts: [
      "Farg'ona",
      "Marg'ilon",
      "Qo'qon",
      "Quvasoy",
      "Bag'dod tumani",
      "Beshariq tumani",
      "Buvayda tumani",
      "Dang'ara tumani",
      "Farg'ona tumani",
      "Furqat tumani",
      "Oltiariq tumani",
      "Qo'shtepa tumani",
      "Quva tumani",
      "Rishton tumani",
      "So'x tumani",
      "Toshloq tumani",
      "Uchko'prik tumani",
      "O'zbekiston tumani",
      "Yozyovon tumani",
    ],
  },
  {
    name: "Jizzax viloyati",
    districts: [
      "Jizzax",
      "Arnasoy tumani",
      "Baxmal tumani",
      "Do'stlik tumani",
      "Forish tumani",
      "G'allaorol tumani",
      "Mirzacho'l tumani",
      "Paxtakor tumani",
      "Sharof Rashidov tumani",
      "Yangiobod tumani",
      "Zafarobod tumani",
      "Zarbdor tumani",
      "Zomin tumani",
    ],
  },
  {
    name: "Namangan viloyati",
    districts: [
      "Namangan",
      "Chortoq tumani",
      "Chust tumani",
      "Kosonsoy tumani",
      "Mingbuloq tumani",
      "Namangan tumani",
      "Norin tumani",
      "Pop tumani",
      "To'raqo'rg'on tumani",
      "Uchqo'rg'on tumani",
      "Uychi tumani",
      "Yangiqo'rg'on tumani",
    ],
  },
  {
    name: "Navoiy viloyati",
    districts: [
      "Navoiy",
      "Zarafshon",
      "Karmana tumani",
      "Konimex tumani",
      "Navbahor tumani",
      "Nurota tumani",
      "Qiziltepa tumani",
      "Tomdi tumani",
      "Uchquduq tumani",
      "Xatirchi tumani",
    ],
  },
  {
    name: "Qashqadaryo viloyati",
    districts: [
      "Qarshi",
      "Shahrisabz",
      "Chiroqchi tumani",
      "Dehqonobod tumani",
      "G'uzor tumani",
      "Kasbi tumani",
      "Kitob tumani",
      "Koson tumani",
      "Ko'kdala tumani",
      "Mirishkor tumani",
      "Muborak tumani",
      "Nishon tumani",
      "Qamashi tumani",
      "Qarshi tumani",
      "Shahrisabz tumani",
      "Yakkabog' tumani",
    ],
  },
  {
    name: "Samarqand viloyati",
    districts: [
      "Samarqand",
      "Kattaqo'rg'on",
      "Bulung'ur tumani",
      "Ishtixon tumani",
      "Jomboy tumani",
      "Kattaqo'rg'on tumani",
      "Narpay tumani",
      "Nurobod tumani",
      "Oqdaryo tumani",
      "Pastdarg'om tumani",
      "Paxtachi tumani",
      "Payariq tumani",
      "Qo'shrabot tumani",
      "Samarqand tumani",
      "Toyloq tumani",
      "Urgut tumani",
    ],
  },
  {
    name: "Sirdaryo viloyati",
    districts: [
      "Guliston",
      "Shirin",
      "Yangiyer",
      "Boyovut tumani",
      "Guliston tumani",
      "Mirzaobod tumani",
      "Oqoltin tumani",
      "Sardoba tumani",
      "Sayxunobod tumani",
      "Sirdaryo tumani",
      "Xovos tumani",
    ],
  },
  {
    name: "Surxondaryo viloyati",
    districts: [
      "Termiz",
      "Angor tumani",
      "Bandixon tumani",
      "Boysun tumani",
      "Denov tumani",
      "Jarqo'rg'on tumani",
      "Muzrabot tumani",
      "Oltinsoy tumani",
      "Qiziriq tumani",
      "Qumqo'rg'on tumani",
      "Sariosiyo tumani",
      "Sherobod tumani",
      "Sho'rchi tumani",
      "Termiz tumani",
      "Uzun tumani",
    ],
  },
  {
    name: "Toshkent viloyati",
    districts: [
      "Nurafshon",
      "Angren",
      "Bekobod",
      "Chirchiq",
      "Olmaliq",
      "Ohangaron",
      "Yangiyo'l",
      "Bekobod tumani",
      "Bo'ka tumani",
      "Bo'stonliq tumani",
      "Chinoz tumani",
      "Ohangaron tumani",
      "Oqqo'rg'on tumani",
      "O'rtachirchiq tumani",
      "Parkent tumani",
      "Piskent tumani",
      "Qibray tumani",
      "Quyichirchiq tumani",
      "Toshkent tumani",
      "Yangiyo'l tumani",
      "Yuqorichirchiq tumani",
      "Zangiota tumani",
    ],
  },
  {
    name: "Xorazm viloyati",
    districts: [
      "Urganch",
      "Xiva",
      "Bog'ot tumani",
      "Gurlan tumani",
      "Hazorasp tumani",
      "Qo'shko'pir tumani",
      "Shovot tumani",
      "Tuproqqal'a tumani",
      "Urganch tumani",
      "Xiva tumani",
      "Xonqa tumani",
      "Yangiariq tumani",
      "Yangibozor tumani",
    ],
  },
  {
    name: "Toshkent shahri",
    districts: [
      "Bektemir tumani",
      "Chilonzor tumani",
      "Mirobod tumani",
      "Mirzo Ulug'bek tumani",
      "Olmazor tumani",
      "Sergeli tumani",
      "Shayxontohur tumani",
      "Uchtepa tumani",
      "Yakkasaroy tumani",
      "Yangihayot tumani",
      "Yashnobod tumani",
      "Yunusobod tumani",
    ],
  },
];
